// Create the chart and store it in a global variable
window.myTreeGraphChart = Highcharts.chart('container', {
    chart: {
        spacingBottom: 30,
        marginRight: 120,
        height: 600
    },
    title: {
        text: 'LN Hierarchical Classification'
    },
    series: [{
        type: 'treegraph',
        keys: ['parent', 'id', 'level'],
        clip: false,
        data: [
            [undefined, 'Lymphoid Neoplasms'], 
            ['Lymphoid Neoplasms', 'LN'],
            ['Lymphoid Neoplasms', 'LN-ID'],
            ['LN', 'NHL'],
            ['LN', 'HL'],
            ['LN', 'LPD'],
            ['LN', 'HL/NHL'],
            ['LN-ID', 'LPD'],
            ['LN-ID', 'NHL'],
            ['LN-ID', 'HL'],
            ['NHL', 'Precursor B-cell neoplasm'],
            ['NHL', 'Mature B-cell neoplasms'],
            ['HL', 'Mature B-cell neoplasms'],
            ['NHL', 'Plasma cell neoplasms and other diseases with paraproteins'],
            ['NHL', 'Precursor T-cell neoplasms'],
            ['NHL', 'Mature T-cell and NK-cell neoplasms'],
            ['LPD', 'Mature T-cell and NK-cell neoplasms'],
            ['HL/NHL', 'Mature B-cell neoplasms'],
            ['LPD', 'Mature B-LPD'],
            ['NHL', 'Mature B-NHL'],
            ['HL', 'Precursor B-cell neoplasm'],
            ['Precursor B-cell neoplasm', 'Reactive B-cell-rich lymphoid proliferations that can mimic lymphoma'],
            ['Precursor B-cell neoplasm', 'IgG4-related disease'],
            ['Precursor B-cell neoplasm', 'Unicentric Castleman disease'],
            ['Precursor B-cell neoplasm', 'Idiopathic multicentric Castleman disease'],
            ['Precursor B-cell neoplasm', 'KSHV/HHV8-associated multicentric Castleman disease'],
            ['Precursor B-cell neoplasm', 'B-cell lymphoblastic leukemias/lymphomas'],
            ['Mature B-cell neoplasms', 'Pre-neoplastic and neoplastic small lymphocytic proliferations'],
            ['Mature B-cell neoplasms', 'Splenic B-cell lymphomas and leukemias'],
            ['Mature B-cell neoplasms', 'LPL'],
            ['Mature B-cell neoplasms', 'MZL'],
            ['Mature B-cell neoplasms', 'FL'],
            ['Mature B-cell neoplasms', 'MCL'],
            ['Mature B-cell neoplasms', 'Transformation of Indolent B-cell lymphomas'],
            ['Mature B-cell neoplasms', 'Large B-cell lymphomas'],
            ['Mature B-cell neoplasms', 'BL'],
            ['Mature B-cell neoplasms', 'KSHV/HHV8 associated'],
            ['Mature B-cell neoplasms', 'LP/LPL-IDD'],
            ['Mature B-cell neoplasms', 'LP/LPL-IDD-IEI'],
            ['Mature B-cell neoplasms', 'HL'],
            ['Plasma cell neoplasms and other diseases with paraproteins', 'Monoclonal gammopathies'],
            ['Plasma cell neoplasms and other diseases with paraproteins', 'Diseases with monoclonal Immunoglobulin deposition'],
            ['Plasma cell neoplasms and other diseases with paraproteins', 'Heavy chain diseases'],
            ['Plasma cell neoplasms and other diseases with paraproteins', 'PCN'],
            ['Precursor T-cell neoplasms', 'T-lymphoblastic leukemia/lymphoma'],
            ['Mature T-cell and NK-cell neoplasms', 'Mature T-cell and NK-cell leukemias'],
            ['Mature T-cell and NK-cell neoplasms', 'CTCL'],
            ['Mature T-cell and NK-cell neoplasms', 'Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas'],
            ['Mature T-cell and NK-cell neoplasms', 'Hepatosplenic T-cell lymphoma'],
            ['Mature T-cell and NK-cell neoplasms', 'ALCL'],
            ['Mature T-cell and NK-cell neoplasms', 'nTFHL'],
            ['Mature T-cell and NK-cell neoplasms', 'PTCL'],
            ['Mature T-cell and NK-cell neoplasms', 'EBV-positive NK/T-cell lymphomas'],
            ['Mature T-cell and NK-cell neoplasms', 'EBV positive T- and NK-cell lymphoid proliferations and lymphomas of childhood'],
            ['Mature B-LPD', 'PTLD'],
            ['Mature B-NHL', 'PTLD'],
            ['Mature T-cell and NK-cell neoplasms', 'PTLD'],
            ['Precursor B-cell neoplasm', 'PTLD'],
            ['Mature B-LPD', 'PID-LPD'],
            ['Mature B-NHL', 'PID-LPD'],
            ['Mature T-cell and NK-cell neoplasms', 'PID-LPD'],
            ['Precursor T-cell neoplasms', 'PID-LPD'],
            ['Precursor B-cell neoplasm', 'PID-LPD'],
            ['Mature B-LPD', 'HIV-LPD'],
            ['Mature B-NHL', 'HIV-LPD'],
            ['Mature T-cell and NK-cell neoplasms', 'HIV-LPD'],
            ['Precursor B-cell neoplasm', 'HIV-LPD'],
            ['Mature B-LPD', 'IAT-LPD'],
            ['Mature B-NHL', 'IAT-LPD'],
            ['Mature T-cell and NK-cell neoplasms', 'IAT-LPD'],
            ['Precursor B-cell neoplasm', 'IAT-LPD'],
            ['B-cell lymphoblastic leukemias/lymphomas', 'B-ALL / LBL,NOS'],
            ['B-cell lymphoblastic leukemias/lymphomas', 'B-ALL / LBL-RGA (b)'],
            ['Pre-neoplastic and neoplastic small lymphocytic proliferations', 'Monoclonal B-cell lymphocytosis, CLL and non-CLL phenotype (MBL)'],
            ['Pre-neoplastic and neoplastic small lymphocytic proliferations', 'Chronic lymphocytic leukemia/small lymphocytic lymphoma (CLL/SLL)'],
            ['Splenic B-cell lymphomas and leukemias', 'HCL'],
            ['Splenic B-cell lymphomas and leukemias', 'SMZL'],
            ['Splenic B-cell lymphomas and leukemias', 'SDRPL'],
            ['Splenic B-cell lymphomas and leukemias', 'SBLPN / B-PLL'],
            ['Splenic B-cell lymphomas and leukemias', 'Splenic B-cell lymphoma/leukemia, unclassifiable (splenic BCL,U)'],
            ['LPL', 'LPL (c )'],
            ['MZL', 'EMZL'],
            ['MZL', 'PCMZL'],
            ['MZL', 'NMZL'],
            ['MZL', 'pNMZL'],
            ['FL', 'classic FL (cFL)'],
            ['FL', 'FL-PED'],
            ['FL', 'Pediatric-type and duodenal FL'],
            ['FL', 'PCFCL'],
            ['FL', 'ISFN'],
            ['MCL', 'ISMCN'],
            ['MCL', 'MCL'],
            ['MCL', 'nnMCL'],
            ['Large B-cell lymphomas', 'DLBCL,NOS'],
            ['Large B-cell lymphomas', 'THRLBCL'],
            ['Large B-cell lymphomas', 'DLBCL'],
            ['Large B-cell lymphomas', 'DLBCL/LBCL immune privileged sites'],
            ['Large B-cell lymphomas', 'PCLBCL, leg type'],
            ['Large B-cell lymphomas', 'EBV-DLBCL, elderly'],
            ['Large B-cell lymphomas', 'DLBCL-CI'],
            ['Large B-cell lymphomas', 'LBCL-fluid overload'],
            ['Large B-cell lymphomas', 'IVBCL'],
            ['Large B-cell lymphomas', 'ALK+DLBCL'],
            ['Large B-cell lymphomas', 'Large B-cell lymphomas with IRF4 rearrangements'],
            ['Large B-cell lymphomas', 'HGBL-11q'],
            ['Large B-cell lymphomas', 'HGBL,NOS'],
            ['Large B-cell lymphomas', 'PBL'],
            ['Large B-cell lymphomas', 'MLBCL'],
            ['Large B-cell lymphomas', 'LYG'],
            ['Large B-cell lymphomas', 'MGZL'],
            ['BL', 'BL'],
            ['KSHV/HHV8 associated', 'PEL'],
            ['KSHV/HHV8 associated', 'KSHV/HHV8-DLBCL'],
            ['KSHV/HHV8 associated', 'KSHV/HHV8-GLPD'],
            ['LP/LPL-IDD', 'Hyperplasias arising in immune deficiency/dysregulation'],
            ['LP/LPL-IDD', 'Polymorphic lymphoproliferative disorders arising in immune deficiency/dysregulation'],
            ['LP/LPL-IDD', 'EBV-positive mucocutaneuous ulcer'],
            ['LP/LPL-IDD', 'Lymphomas arising in immune deficiency/dysregulation'],
            ['LP/LPL-IDD-IEI', 'Inborn error of immunity-associated lymphoid proliferations and lymphomas'],
            ['HL', 'CHL'],
            ['HL', 'NLPHL'],
            ['Monoclonal gammopathies', 'CAD'],
            ['Monoclonal gammopathies', 'MGUS'],
            ['Monoclonal gammopathies', 'IgM-MGUS'],
            ['Monoclonal gammopathies', 'non-IgM-MGUS'],
            ['Monoclonal gammopathies', 'MGRS'],
            ['Diseases with monoclonal Immunoglobulin deposition', 'AL'],
            ['Diseases with monoclonal Immunoglobulin deposition', 'Monoclonal immunoglobulin deposition disease'],
            ['Heavy chain diseases', 'Mu heavy chain'],
            ['Heavy chain diseases', 'Gamma heavy chain disease'],
            ['Heavy chain diseases', 'Alpha heavy chain disease'],
            ['PCN', 'Plasmacytoma bone'],
            ['PCN', 'Plasmacytoma extraosseous'],
            ['PCN', 'PCM'],
            ['PCN', 'PCN-with syndrome'],
            ['T-lymphoblastic leukemia/lymphoma', 'T-ALL/LBL, NOS'],
            ['Mature T-cell and NK-cell leukemias', 'T-PLL'],
            ['Mature T-cell and NK-cell leukemias', 'T-LGLL'],
            ['Mature T-cell and NK-cell leukemias', 'ATLL'],
            ['Mature T-cell and NK-cell leukemias', 'ANKL'],
            ['Mature T-cell and NK-cell leukemias', 'SS'],
            ['Mature T-cell and NK-cell leukemias', 'NK-LGLL'],
            ['CTCL', 'SPTCL'],
            ['CTCL', 'PCGD-TCL'],
            ['CTCL', 'PCCD8-TCL'],
            ['CTCL', 'PCTL,NOS'],
            ['CTCL', 'PCCD4-TCL'],
            ['CTCL', 'MF'],
            ['CTCL', 'CD30+PCLPD'],
            ['Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas', 'Indolent T-cell lymphoma of the gastrointestinal tract'],
            ['Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas', 'iNKLPD'],
            ['Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas', 'Enteropathy-associated T-cell lymphoma (EATL)'],
            ['Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas', 'Intraepithelial (intestinal) T-cell lymphoma -in -situ (EATL-in situ)'],
            ['Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas', 'Monomorphic epitheliotropic intestinal T-cell lymphoma'],
            ['Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas', 'Intestinal T-cell lymphoma, NOS'],
            ['Hepatosplenic T-cell lymphoma', 'HSTL'],
            ['ALCL', 'ALK+ ALCL'],
            ['ALCL', 'ALK- ALCL'],
            ['ALCL', 'BIA-ALCL'],
            ['nTFHL', 'nTFHL-AI'],
            ['nTFHL', 'nTFHL-F'],
            ['nTFHL', 'nTFHL-NOS'],
            ['EBV-positive NK/T-cell lymphomas', 'EBV-positive nodal T- and NK-cell lymphoma'],
            ['EBV-positive NK/T-cell lymphomas', 'ENKTL'],
            ['EBV positive T- and NK-cell lymphoid proliferations and lymphomas of childhood', 'Severe mosquito bite allergy'],
            ['EBV positive T- and NK-cell lymphoid proliferations and lymphomas of childhood', 'Systemic EBV-positive T-cell lymphoma of childhood'],
            ['EBV positive T- and NK-cell lymphoid proliferations and lymphomas of childhood', 'Systemic chronic active EBV disease'],
            ['EBV positive T- and NK-cell lymphoid proliferations and lymphomas of childhood', 'Hydroa vacciniforme lymphoproliferative disorder (HVL)'],
            ['PTLD', 'PTLD-PH'],
            ['PTLD', 'PTLD-IM-like'],
            ['PTLD', 'PTLD-M-B-cell'],
            ['PTLD', 'PTLD-M-T-cell'],
            ['PTLD', 'PTLD-CHL'],
            ['PID-LPD', 'PID-LPD-P'],
            ['PID-LPD', 'PID-LPD-B-cell'],
            ['PID-LPD', 'PID-LPD-T or NK cell'],
            ['PID-LPD', 'PID-T-ALL/LBL'],
            ['PID-LPD', 'PID-CHL'],
            ['HIV-LPD', 'HIV-LPD-P'],
            ['HIV-LPD', 'HIV-LPD-B-cell'],
            ['HIV-LPD', 'HIV-LPD-T or NK cell'],
            ['HIV-LPD', 'HIV-CHL'],
            ['IAT-LPD', 'IAT-LPD-P'],
            ['IAT-LPD', 'IAT-LPD-B-cell'],
            ['IAT-LPD', 'IAT-LPD-T or NK cell'],
            ['IAT-LPD', 'IAT-CHL'],
            ['B-ALL / LBL,NOS', 'B-ALL or LBL,NOS'],
            ['B-ALL / LBL-RGA (b)', 'B-ALL with other defined genetic abnormalities'],
            ['Monoclonal B-cell lymphocytosis, CLL and non-CLL phenotype (MBL)', 'MBL (Low-count MBL or clinal B-cell expansion, CLL/SLL-type MBL, non-CLL/SLL-type MBL)'],
            ['Chronic lymphocytic leukemia/small lymphocytic lymphoma (CLL/SLL)', 'CLL or SLL'],
            ['SBLPN / B-PLL', 'SBLPN or B-PLL'],
            ['LPL (c )', 'IgM-LPL/WM type, Non-WM type LPL'],
            ['EMZL', 'EMZL-type, MALT (e)'],
            ['classic FL (cFL)', 'follicular large B-cell lymphoma (FLBL), FL with uncommon features (uFL)'],
            ['Pediatric-type and duodenal FL', 'Pediatric-type FL, duodenal FL'],
            ['DLBCL,NOS', 'DLBCL,NOS (h )'],
            ['THRLBCL', 'THRLBCL (h )'],
            ['DLBCL', 'DLBCL/HGBL-MYC/BCL2'],
            ['DLBCL/LBCL immune privileged sites', 'Primary DLBCL/LBCL of the CNS, Primary LBCL of the viteroretina, Primary LBCL of the testis'],
            ['DLBCL-CI', 'DLBCL Fibrin-associated'],
            ['ALK+DLBCL', 'ALK+DLBCL (h )'],
            ['HGBL,NOS', 'HGBL,NOS ("double hit"-DHITsig)'],
            ['PBL', 'PBL (h )'],
            ['MLBCL', 'MLBCL (h )'],
            ['BL', 'EBV-positive BL, EBV-negative BL'],
            ['PEL', 'PEL (h ),  EC-PEL'],
            ['CHL', 'LRCHL'],
            ['CHL', 'MCCHL'],
            ['CHL', 'LDCHL'],
            ['CHL', 'NSCHL'],
            ['CHL', 'CHL, NOS'],
            ['Plasmacytoma bone', 'Plasmacytoma bone'],
            ['Plasmacytoma extraosseous', 'Plasmacytoma extraosseous'],
            ['PCN-with syndrome', 'PCN-POEMS, PCN-TEMPI, PCN-AESOP'],
            ['T-ALL/LBL, NOS', 'T-ALL, LBL'],
            ['CD30+PCLPD', 'C-ALCL'],
            ['CD30+PCLPD', 'Lyp'],

        ],
        marker: {
            symbol: 'circle',
            radius: 6,
            fillColor: '#ffffff',
            lineWidth: 3
        },
        dataLabels: {
            align: 'left',
            pointFormat: '{point.id}',
            style: {
                color: '#000000',
                textOutline: '3px #ffffff',
                whiteSpace: 'nowrap'
            },
            x: 24,
            crop: false,
            overflow: 'none'
        },
        levels: [
            {
                level: 1,
                levelIsConstant: false
            },
            {
                level: 2,
                colorByPoint: true
            },
            {
                level: 3,
                colorVariation: {
                    key: 'brightness',
                    to: -0.5
                }
            },
            {
                level: 4,
                colorVariation: {
                    key: 'brightness',
                    to: 0.5
                }
            },
            {
                level: 6,
                dataLabels: {
                    x: 10
                },
                marker: {
                    radius: 4
                }
            }
        ]
    }]
});
