// Create the chart and store it in a global variable
window.myTreeGraphChart = Highcharts.chart('container', {
    chart: {
        spacingBottom: 30,
        marginRight: 120,
        height: 600
    },
    title: {
        text: 'LN Hierarchical Classification'
    },
    series: [{
        type: 'treegraph',
        keys: ['parent', 'id', 'level'],
        clip: false,
        data: [
            [undefined, 'Lymphoid Neoplasms'], 
            ['Lymphoid Neoplasms', 'LN', '1'],
            ['Lymphoid Neoplasms', 'LN-ID', '1'],
            ['LN', 'NHL', '2'],
            ['LN', 'HL', '2'],
            ['LN', 'LPD', '2'],
            ['LN', 'HL/NHL', '2'],
            ['LN-ID', 'LPD', '2'],
            ['LN-ID', 'NHL', '2'],
            ['LN-ID', 'HL', '2'],
            ['NHL', 'Precursor B-cell neoplasm', '3'],
            ['NHL', 'Mature B-cell neoplasms', '3'],
            ['HL', 'Mature B-cell neoplasms', '3'],
            ['NHL', 'Plasma cell neoplasms and other diseases with paraproteins', '3'],
            ['NHL', 'Precursor T-cell neoplasms', '3'],
            ['NHL', 'Mature T-cell and NK-cell neoplasms', '3'],
            ['LPD', 'Mature T-cell and NK-cell neoplasms', '3'],
            ['HL/NHL', 'Mature B-cell neoplasms', '3'],
            ['LPD', 'Mature B-LPD', '3'],
            ['NHL', 'Mature B-NHL', '3'],
            ['HL', 'Precursor B-cell neoplasm', '3'],
            ['Precursor B-cell neoplasm', 'Reactive B-cell-rich lymphoid proliferations that can mimic lymphoma', '4'],
            ['Precursor B-cell neoplasm', 'IgG4-related disease', '4'],
            ['Precursor B-cell neoplasm', 'Unicentric Castleman disease', '4'],
            ['Precursor B-cell neoplasm', 'Idiopathic multicentric Castleman disease', '4'],
            ['Precursor B-cell neoplasm', 'KSHV/HHV8-associated multicentric Castleman disease', '4'],
            ['Precursor B-cell neoplasm', 'B-cell lymphoblastic leukemias/lymphomas', '4'],
            ['Mature B-cell neoplasms', 'Pre-neoplastic and neoplastic small lymphocytic proliferations', '4'],
            ['Mature B-cell neoplasms', 'Splenic B-cell lymphomas and leukemias', '4'],
            ['Mature B-cell neoplasms', 'LPL', '4'],
            ['Mature B-cell neoplasms', 'MZL', '4'],
            ['Mature B-cell neoplasms', 'FL', '4'],
            ['Mature B-cell neoplasms', 'MCL', '4'],
            ['Mature B-cell neoplasms', 'Transformation of Indolent B-cell lymphomas', '4'],
            ['Mature B-cell neoplasms', 'Large B-cell lymphomas', '4'],
            ['Mature B-cell neoplasms', 'BL', '4'],
            ['Mature B-cell neoplasms', 'KSHV/HHV8 associated', '4'],
            ['Mature B-cell neoplasms', 'LP/LPL-IDD', '4'],
            ['Mature B-cell neoplasms', 'LP/LPL-IDD-IEI', '4'],
            ['Mature B-cell neoplasms', 'HL', '4'],
            ['Plasma cell neoplasms and other diseases with paraproteins', 'Monoclonal gammopathies', '4'],
            ['Plasma cell neoplasms and other diseases with paraproteins', 'Diseases with monoclonal Immunoglobulin deposition', '4'],
            ['Plasma cell neoplasms and other diseases with paraproteins', 'Heavy chain diseases', '4'],
            ['Plasma cell neoplasms and other diseases with paraproteins', 'PCN', '4'],
            ['Precursor T-cell neoplasms', 'T-lymphoblastic leukemia/lymphoma', '4'],
            ['Mature T-cell and NK-cell neoplasms', 'Mature T-cell and NK-cell leukemias', '4'],
            ['Mature T-cell and NK-cell neoplasms', 'CTCL', '4'],
            ['Mature T-cell and NK-cell neoplasms', 'Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas', '4'],
            ['Mature T-cell and NK-cell neoplasms', 'Hepatosplenic T-cell lymphoma', '4'],
            ['Mature T-cell and NK-cell neoplasms', 'ALCL', '4'],
            ['Mature T-cell and NK-cell neoplasms', 'nTFHL', '4'],
            ['Mature T-cell and NK-cell neoplasms', 'PTCL', '4'],
            ['Mature T-cell and NK-cell neoplasms', 'EBV-positive NK/T-cell lymphomas', '4'],
            ['Mature T-cell and NK-cell neoplasms', 'EBV positive T- and NK-cell lymphoid proliferations and lymphomas of childhood', '4'],
            ['Mature B-LPD', 'PTLD', '4'],
            ['Mature B-NHL', 'PTLD', '4'],
            ['Mature T-cell and NK-cell neoplasms', 'PTLD', '4'],
            ['Precursor B-cell neoplasm', 'PTLD', '4'],
            ['Mature B-LPD', 'PID-LPD', '4'],
            ['Mature B-NHL', 'PID-LPD', '4'],
            ['Mature T-cell and NK-cell neoplasms', 'PID-LPD', '4'],
            ['Precursor T-cell neoplasms', 'PID-LPD', '4'],
            ['Precursor B-cell neoplasm', 'PID-LPD', '4'],
            ['Mature B-LPD', 'HIV-LPD', '4'],
            ['Mature B-NHL', 'HIV-LPD', '4'],
            ['Mature T-cell and NK-cell neoplasms', 'HIV-LPD', '4'],
            ['Precursor B-cell neoplasm', 'HIV-LPD', '4'],
            ['Mature B-LPD', 'IAT-LPD', '4'],
            ['Mature B-NHL', 'IAT-LPD', '4'],
            ['Mature T-cell and NK-cell neoplasms', 'IAT-LPD', '4'],
            ['Precursor B-cell neoplasm', 'IAT-LPD', '4'],
            ['B-cell lymphoblastic leukemias/lymphomas', 'B-ALL / LBL,NOS', '5'],
            ['B-cell lymphoblastic leukemias/lymphomas', 'B-ALL / LBL-RGA (b)', '5'],
            ['Pre-neoplastic and neoplastic small lymphocytic proliferations', 'Monoclonal B-cell lymphocytosis, CLL and non-CLL phenotype (MBL)', '5'],
            ['Pre-neoplastic and neoplastic small lymphocytic proliferations', 'Chronic lymphocytic leukemia/small lymphocytic lymphoma (CLL/SLL)', '5'],
            ['Splenic B-cell lymphomas and leukemias', 'HCL', '5'],
            ['Splenic B-cell lymphomas and leukemias', 'SMZL', '5'],
            ['Splenic B-cell lymphomas and leukemias', 'SDRPL', '5'],
            ['Splenic B-cell lymphomas and leukemias', 'SBLPN / B-PLL', '5'],
            ['Splenic B-cell lymphomas and leukemias', 'Splenic B-cell lymphoma/leukemia, unclassifiable (splenic BCL,U)', '5'],
            ['LPL', 'LPL (c )', '5'],
            ['MZL', 'EMZL', '5'],
            ['MZL', 'PCMZL', '5'],
            ['MZL', 'NMZL', '5'],
            ['MZL', 'pNMZL', '5'],
            ['FL', 'classic FL (cFL)', '5'],
            ['FL', 'FL-PED', '5'],
            ['FL', 'Pediatric-type and duodenal FL', '5'],
            ['FL', 'PCFCL', '5'],
            ['FL', 'ISFN', '5'],
            ['MCL', 'ISMCN', '5'],
            ['MCL', 'MCL', '5'],
            ['MCL', 'nnMCL', '5'],
            ['Large B-cell lymphomas', 'DLBCL,NOS', '5'],
            ['Large B-cell lymphomas', 'THRLBCL', '5'],
            ['Large B-cell lymphomas', 'DLBCL', '5'],
            ['Large B-cell lymphomas', 'DLBCL/LBCL immune privileged sites', '5'],
            ['Large B-cell lymphomas', 'PCLBCL, leg type', '5'],
            ['Large B-cell lymphomas', 'EBV-DLBCL, elderly', '5'],
            ['Large B-cell lymphomas', 'DLBCL-CI', '5'],
            ['Large B-cell lymphomas', 'LBCL-fluid overload', '5'],
            ['Large B-cell lymphomas', 'IVBCL', '5'],
            ['Large B-cell lymphomas', 'ALK+DLBCL', '5'],
            ['Large B-cell lymphomas', 'Large B-cell lymphomas with IRF4 rearrangements', '5'],
            ['Large B-cell lymphomas', 'HGBL-11q', '5'],
            ['Large B-cell lymphomas', 'HGBL,NOS', '5'],
            ['Large B-cell lymphomas', 'PBL', '5'],
            ['Large B-cell lymphomas', 'MLBCL', '5'],
            ['Large B-cell lymphomas', 'LYG', '5'],
            ['Large B-cell lymphomas', 'MGZL', '5'],
            ['BL', 'BL', '5'],
            ['KSHV/HHV8 associated', 'PEL', '5'],
            ['KSHV/HHV8 associated', 'KSHV/HHV8-DLBCL', '5'],
            ['KSHV/HHV8 associated', 'KSHV/HHV8-GLPD', '5'],
            ['LP/LPL-IDD', 'Hyperplasias arising in immune deficiency/dysregulation', '5'],
            ['LP/LPL-IDD', 'Polymorphic lymphoproliferative disorders arising in immune deficiency/dysregulation', '5'],
            ['LP/LPL-IDD', 'EBV-positive mucocutaneuous ulcer', '5'],
            ['LP/LPL-IDD', 'Lymphomas arising in immune deficiency/dysregulation', '5'],
            ['LP/LPL-IDD-IEI', 'Inborn error of immunity-associated lymphoid proliferations and lymphomas', '5'],
            ['HL', 'CHL', '5'],
            ['HL', 'NLPHL', '5'],
            ['Monoclonal gammopathies', 'CAD', '5'],
            ['Monoclonal gammopathies', 'MGUS', '5'],
            ['Monoclonal gammopathies', 'IgM-MGUS', '5'],
            ['Monoclonal gammopathies', 'non-IgM-MGUS', '5'],
            ['Monoclonal gammopathies', 'MGRS', '5'],
            ['Diseases with monoclonal Immunoglobulin deposition', 'AL', '5'],
            ['Diseases with monoclonal Immunoglobulin deposition', 'Monoclonal immunoglobulin deposition disease', '5'],
            ['Heavy chain diseases', 'Mu heavy chain', '5'],
            ['Heavy chain diseases', 'Gamma heavy chain disease', '5'],
            ['Heavy chain diseases', 'Alpha heavy chain disease', '5'],
            ['PCN', 'Plasmacytoma bone', '5'],
            ['PCN', 'Plasmacytoma extraosseous', '5'],
            ['PCN', 'PCM', '5'],
            ['PCN', 'PCN-with syndrome', '5'],
            ['T-lymphoblastic leukemia/lymphoma', 'T-ALL/LBL, NOS', '5'],
            ['Mature T-cell and NK-cell leukemias', 'T-PLL', '5'],
            ['Mature T-cell and NK-cell leukemias', 'T-LGLL', '5'],
            ['Mature T-cell and NK-cell leukemias', 'ATLL', '5'],
            ['Mature T-cell and NK-cell leukemias', 'ANKL', '5'],
            ['Mature T-cell and NK-cell leukemias', 'SS', '5'],
            ['Mature T-cell and NK-cell leukemias', 'NK-LGLL', '5'],
            ['CTCL', 'SPTCL', '5'],
            ['CTCL', 'PCGD-TCL', '5'],
            ['CTCL', 'PCCD8-TCL', '5'],
            ['CTCL', 'PCTL,NOS', '5'],
            ['CTCL', 'PCCD4-TCL', '5'],
            ['CTCL', 'MF', '5'],
            ['CTCL', 'CD30+PCLPD', '5'],
            ['Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas', 'Indolent T-cell lymphoma of the gastrointestinal tract', '5'],
            ['Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas', 'iNKLPD', '5'],
            ['Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas', 'Enteropathy-associated T-cell lymphoma (EATL)', '5'],
            ['Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas', 'Intraepithelial (intestinal) T-cell lymphoma -in -situ (EATL-in situ)', '5'],
            ['Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas', 'Monomorphic epitheliotropic intestinal T-cell lymphoma', '5'],
            ['Intestinal T-cell and NK-cell lymphoid proliferations and lymphomas', 'Intestinal T-cell lymphoma, NOS', '5'],
            ['Hepatosplenic T-cell lymphoma', 'HSTL', '5'],
            ['ALCL', 'ALK+ ALCL', '5'],
            ['ALCL', 'ALK- ALCL', '5'],
            ['ALCL', 'BIA-ALCL', '5'],
            ['nTFHL', 'nTFHL-AI', '5'],
            ['nTFHL', 'nTFHL-F', '5'],
            ['nTFHL', 'nTFHL-NOS', '5'],
            ['EBV-positive NK/T-cell lymphomas', 'EBV-positive nodal T- and NK-cell lymphoma', '5'],
            ['EBV-positive NK/T-cell lymphomas', 'ENKTL', '5'],
            ['EBV positive T- and NK-cell lymphoid proliferations and lymphomas of childhood', 'Severe mosquito bite allergy', '5'],
            ['EBV positive T- and NK-cell lymphoid proliferations and lymphomas of childhood', 'Systemic EBV-positive T-cell lymphoma of childhood', '5'],
            ['EBV positive T- and NK-cell lymphoid proliferations and lymphomas of childhood', 'Systemic chronic active EBV disease', '5'],
            ['EBV positive T- and NK-cell lymphoid proliferations and lymphomas of childhood', 'Hydroa vacciniforme lymphoproliferative disorder (HVL)', '5'],
            ['PTLD', 'PTLD-PH', '5'],
            ['PTLD', 'PTLD-IM-like', '5'],
            ['PTLD', 'PTLD-M-B-cell', '5'],
            ['PTLD', 'PTLD-M-T-cell', '5'],
            ['PTLD', 'PTLD-CHL', '5'],
            ['PID-LPD', 'PID-LPD-P', '5'],
            ['PID-LPD', 'PID-LPD-B-cell', '5'],
            ['PID-LPD', 'PID-LPD-T or NK cell', '5'],
            ['PID-LPD', 'PID-T-ALL/LBL', '5'],
            ['PID-LPD', 'PID-CHL', '5'],
            ['HIV-LPD', 'HIV-LPD-P', '5'],
            ['HIV-LPD', 'HIV-LPD-B-cell', '5'],
            ['HIV-LPD', 'HIV-LPD-T or NK cell', '5'],
            ['HIV-LPD', 'HIV-CHL', '5'],
            ['IAT-LPD', 'IAT-LPD-P', '5'],
            ['IAT-LPD', 'IAT-LPD-B-cell', '5'],
            ['IAT-LPD', 'IAT-LPD-T or NK cell', '5'],
            ['IAT-LPD', 'IAT-CHL', '5'],
            ['B-ALL / LBL,NOS', 'B-ALL or LBL,NOS', '6'],
            ['B-ALL / LBL-RGA (b)', 'B-ALL with other defined genetic abnormalities', '6'],
            ['Monoclonal B-cell lymphocytosis, CLL and non-CLL phenotype (MBL)', 'MBL (Low-count MBL or clinal B-cell expansion, CLL/SLL-type MBL, non-CLL/SLL-type MBL)', '6'],
            ['Chronic lymphocytic leukemia/small lymphocytic lymphoma (CLL/SLL)', 'CLL or SLL', '6'],
            ['SBLPN / B-PLL', 'SBLPN or B-PLL', '6'],
            ['LPL (c )', 'IgM-LPL/WM type, Non-WM type LPL', '6'],
            ['EMZL', 'EMZL-type, MALT (e)', '6'],
            ['classic FL (cFL)', 'follicular large B-cell lymphoma (FLBL), FL with uncommon features (uFL)', '6'],
            ['Pediatric-type and duodenal FL', 'Pediatric-type FL, duodenal FL', '6'],
            ['DLBCL,NOS', 'DLBCL,NOS (h )', '6'],
            ['THRLBCL', 'THRLBCL (h )', '6'],
            ['DLBCL', 'DLBCL/HGBL-MYC/BCL2', '6'],
            ['DLBCL/LBCL immune privileged sites', 'Primary DLBCL/LBCL of the CNS, Primary LBCL of the viteroretina, Primary LBCL of the testis', '6'],
            ['DLBCL-CI', 'DLBCL Fibrin-associated', '6'],
            ['ALK+DLBCL', 'ALK+DLBCL (h )', '6'],
            ['HGBL,NOS', 'HGBL,NOS ("double hit"-DHITsig)', '6'],
            ['PBL', 'PBL (h )', '6'],
            ['MLBCL', 'MLBCL (h )', '6'],
            ['BL', 'EBV-positive BL, EBV-negative BL', '6'],
            ['PEL', 'PEL (h ),  EC-PEL', '6'],
            ['CHL', 'LRCHL', '6'],
            ['CHL', 'MCCHL', '6'],
            ['CHL', 'LDCHL', '6'],
            ['CHL', 'NSCHL', '6'],
            ['CHL', 'CHL, NOS', '6'],
            ['Plasmacytoma bone', 'Plasmacytoma bone', '6'],
            ['Plasmacytoma extraosseous', 'Plasmacytoma extraosseous', '6'],
            ['PCN-with syndrome', 'PCN-POEMS, PCN-TEMPI, PCN-AESOP', '6'],
            ['T-ALL/LBL, NOS', 'T-ALL, LBL', '6'],
            ['CD30+PCLPD', 'C-ALCL', '6'],
            ['CD30+PCLPD', 'Lyp', '6'],
            

        ],
        marker: {
            symbol: 'circle',
            radius: 6,
            fillColor: '#ffffff',
            lineWidth: 3
        },
        dataLabels: {
            align: 'left',
            pointFormat: '{point.id}',
            style: {
                color: '#000000',
                textOutline: '3px #ffffff',
                whiteSpace: 'nowrap'
            },
            x: 24,
            crop: false,
            overflow: 'none'
        },
        levels: [
            {
                level: 1,
                levelIsConstant: false
            },
            {
                level: 2,
                colorByPoint: true
            },
            {
                level: 3,
                colorVariation: {
                    key: 'brightness',
                    to: -0.5
                }
            },
            {
                level: 4,
                colorVariation: {
                    key: 'brightness',
                    to: 0.5
                }
            },
            {
                level: 6,
                dataLabels: {
                    x: 10
                },
                marker: {
                    radius: 4
                }
            }
        ]
    }]
});
